### ISSUE TITLE
Authors list on Zenodo

### ISSUE THREAD

**Issue by rajaben-ali** [rajaben-ali/cri-openscience-g9#7]
Associate ORCID and Github to researcher profile on Zenodo

**Comment by mthldls** [comment]
https://orcid.org/0000-0002-2057-981X
My zenodo account is telling me that it is connect both with github and orcid, so it is done normally ...

**Comment by rajaben-ali** [comment]
@mthldls, we will close the issue when everyone did it. We need to have everybody's name on our project on zenodo: we will make a new release as soon as everyone linked their zenodo to orcid and github @mthldls @kozload @ssmarmol
